import styled from '@emotion/styled'
import Head from 'next/head'

const Layout = styled('div')`
  display: flex;
  width: 100%;
  height: 100%;

  padding: 20px;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Toolbox</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        asdasdasd
      </Layout>
    </>
  )
}
